version: "3"
services:
  db:
    image: "automation"
    container_name: "automation"
    ports:
      - "54320:5432"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:54320"]
        interval: 30s
        timeout: 10s
        retries: 5
